name: Daily Paper Collection

on:
  schedule:
    # 毎日18:00 JST (09:00 UTC) に実行
    - cron: '0 9 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  collect-papers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create logs directory
      run: mkdir -p logs

    - name: Run paper collection
      env:
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      run: |
        echo "Starting paper collection at $(date)"
        python main.py
        echo "Paper collection completed at $(date)"

    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: paper-collection-logs-${{ github.run_number }}
        path: logs/
        retention-days: 30
